server:
  port: 8081

spring:
  datasource:
    url: '@db.url@'
    username: ${APP_DB_USERNAME}
    password: ${APP_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: false
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      jdbc:
        time_zone: UTC

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

logging:
  level:
    com.example.product: DEBUG

inventory:
  service:
    base-url: '@inventory.url@'

soap:
  calculator:
    wsdl: '@calculator.wsdl.url@'    
