db.url=jdbc:mariadb://${APP_DB_HOST}:${APP_DB_PORT}/liverlivecode
inventory.url=${INVENTORY_SERVICE_URL}
queue.capacity=10
pool.size=5
cache.initialCapacity=100
cache.maximumSize=1000
cache.expireAfterWrite=10