server:
  port: 8080

spring:
  datasource:
    url: '@db.url@'
    username: ${APP_DB_USERNAME}
    password: ${APP_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        globally_quoted_identifiers: false
        format_sql: false
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      jdbc:
        time_zone: UTC

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,metrics

logging:
  level:
    com.example.product: WARN
    io.github.resilience4j: WARN

inventory:
  service:
    base-url: '@inventory.url@'

soap:
  calculator:
    wsdl: '@calculator.wsdl.url@'
  countryinfo:
    wsdl: '@countryinfo.wsdl.url@'   
