spring:
  profiles:
    active: '@activatedProperties@'
  application:
    name: inventory-service

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api/v1/api-docs

app:
  logging:
    slow-request-threshold-ms: 1000

logging:
  file:
    name: logs/app.log
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(%-5level) %clr([${spring.application.name}]){blue} %clr([%thread]){magenta} %clr([%X{traceId:-NOTRACE}]){yellow} %clr(%logger{36}){cyan} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [${spring.application.name}] [%thread] [%X{traceId:-NOTRACEID}] %logger{40}:%L - %msg%n"
  logback:
    rolling policy:
      max-file-size: 20MB
      max-history: 15
      total-size-cap: 500MB
      file-name-pattern: logs/app-%d{yyyy-MM-dd}.%i.log.gz
  level:
    web: INFO
    hogar.codelive.inventory: INFO
    io.github.resilience4j: INFO
    com.zaxxer.hikari: WARN
    org.hibernate: WARN
    org.hibernate.SQL: WARN
    org.hibernate.orm.connections.pooling: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.springframework.boot.autoconfigure.security.UserDetailsServiceAutoConfiguration: WARN
    org.hibernate.engine.transaction.jta.platform.internal.JtaPlatformInitiator: WARN
    org.springframework.boot.devtools.restart.ChangeableUrls: ERROR

queue:
  capacity: 10

pool:
  size: 5

cache:
  initialCapacity: 100
  maximumSize: 1000
  expireAfterWrite: 2


